### ISSUE TITLE
Respond here to get added as a collaborator

### ISSUE THREAD

**Issue by joesocktwo** [joesocktwo/Wall-Street-Bets-Master-Doc#2]
This is basically a signup sheet. Respond here and I'll add you to the repository.

**Comment by adwydman** [comment]
Hey, I work with Github everyday as a programmer and would like to help out!

**Comment by notmemoto** [comment]
I'd like to be added.

**Comment by JurysOut** [comment]
Yes boss sign me up

**Comment by Cannabiz-420** [comment]
I'm so ready for this :)

**Comment by Durrtd** [comment]
Add

**Comment by stevehemingway** [comment]
Add me please!

**Comment by tshallenberger** [comment]
I'd like to be added as well

**Comment by Shift-F9** [comment]
I would like to be added!

**Comment by GokuDoku** [comment]
Please add me I’m really looking forward to contributing to this project. It feels like something groundbreaking and this distributed approach is brilliant. I can try and recruit a few more brilliant people into this as well (friends high up in finance, VC, etc)

**Comment by marcospedreiro** [comment]
I can assist as a collaborator.

**Comment by isit5pmnyet** [comment]
Add me

**Comment by tendiequest** [comment]
Work in Fintech as an engineer, this is an alt account and I’d like to help.

**Comment by Michanne** [comment]
Add me

**Comment by NeptunesFleshlight** [comment]
Add me as well! I'm working on compiling sources to help newcomers learn
more about the repo market.

**Comment by AlphaBetaWhisky** [comment]
I would like to join.

**Comment by Gutray** [comment]
I would like to join as well.

**Comment by Expect-The-Opposite** [comment]
Add please. Bachelor of arts, Finance focused; thanks in advance.

**Comment by brody-taylor** [comment]
Hey would love to join the group, sign me up!

**Comment by ptlorenz** [comment]
Let's get this bear gang party started... add me please

**Comment by Troggys** [comment]
Please add me. MBA with intl finance focus.

**Comment by tendy-capital** [comment]
Please add me.

**Comment by anonnyc2020** [comment]
Please add me as a collab.

**Comment by Adamrch** [comment]
add me please

**Comment by M4SID** [comment]
I would like to be added as well. Legal background here.

**Comment by 7M-07IK** [comment]
add me please

**Comment by jamesjryan** [comment]
Count me in please.

**Comment by Lacheankey** [comment]
I'd like to join and learn what I can from you all.

**Comment by oldirtywizard** [comment]
I'm down

**Comment by angels27** [comment]
Sign me up

**Comment by wolfshot7** [comment]
Add me please

**Comment by RaphizZGithub** [comment]
Hey I'd like to help you guys ! Thank you !

**Comment by tonykylim** [comment]
Wsb unite

**Comment by flexiboy98** [comment]
I would like to be a part of this! Add me please! Thanks

**Comment by ambrusq** [comment]
Hi, I would like to be added too, thanks

**Comment by technicalanalyst11** [comment]
Welp I’m here :)

**Comment by wwang8421** [comment]
I'm down to help, thanks

**Comment by identileo** [comment]
Sign me up!

**Comment by nicolls1** [comment]
Interested! Also the discord link is expired. I think there is a checkbox or something to have the link be permanent.

**Comment by FLsurf7** [comment]
Interested in collaborating

**Comment by jonathanyi-verys** [comment]
Count me in!

**Comment by Hell0W0rldcp** [comment]
I would like to help in FA

**Comment by trakout** [comment]
Let's do it

**Comment by drefll** [comment]
Add me. How can I help?

**Comment by jlesniak2018** [comment]
Want to help, lmk how

**Comment by BetaHawk** [comment]
Please add me.

**Comment by Chaos-Maple** [comment]
It's Chaos in here.

**Comment by hidotp** [comment]
Count me in!

**Comment by samuelmutty** [comment]
A little bit late but I’m down if you’re still accepting people. Not currently in finance but got my degree in it and know my shit reasonably well.
