### ISSUE TITLE
Having apostrophes and question marks in a filename is really, really awkward

### ISSUE THREAD

**Issue by stevehemingway** [joesocktwo/Wall-Street-Bets-Master-Doc#3]
File name: 'What's repo market?' is problematic.

I can clone via bash in WSL, and via Source Tree, but not via Tortoise Git.

**Comment by joesocktwo** [comment]
Noted. I'm leaving this up to the crowd to handle. I'm taking a fairly hands-off approach to this, so feel free to make edits and changes as you see fit.

**Comment by adwydman** [comment]
I removed the directory, thanks for the heads up
